/* empty css                      */import{a as m,S as g,i as a}from"./assets/vendor-CIF6YjI2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const y="56203683-dd16d7902fd33711f42dee53b",h="https://pixabay.com/api/";async function b(s){try{return(await m.get(h,{params:{key:y,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40}})).data}catch(r){throw console.error("Error",r),r}}const L=new g(".gallery a",{captionsData:"alt",captionDelay:250}),u=document.querySelector(".gallery"),c=document.querySelector(".loader");function w(s){d();const r=s.map(({webformatURL:o,largeImageURL:n,tags:e,likes:t,views:i,comments:f,downloads:p})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${n}">
            <img class="gallery-image" src="${o}" alt="${e}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b> ${t}</p>
            <p class="info-item"><b>Views</b> ${i}</p>
            <p class="info-item"><b>Comments</b> ${f}</p>
            <p class="info-item"><b>Downloads</b> ${p}</p>
          </div>
        </li>
      `).join("");u.insertAdjacentHTML("beforeend",r),L.refresh()}function d(){u.innerHTML=""}function S(){c&&c.classList.remove("is-hidden")}function q(){c?c.classList.add("is-hidden"):console.warn("Element is apsent")}const l=document.querySelector(".form");document.querySelector(".input");l&&l.addEventListener("submit",async s=>{s.preventDefault(),d();const r=s.currentTarget.elements["search-text"].value.trim();if(!r){a.warning({title:"Warning",message:"Будь ласка, введіть значення!",position:"topRight"});return}S();try{const o=await b(r);if(!o.hits||o.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}w(o.hits),a.success({title:"Success",message:`Ми знайшли ${o.hits.length} зображень!`,position:"topRight"})}catch(o){a.error({title:"Error",message:"Сталася помилка під час завантаження. Спробуйте пізніше!",position:"topRight"}),console.error("Fetch error:",o)}finally{q(),s.target.reset()}});
//# sourceMappingURL=index.js.map
